{{- if .Values.enabled }}
apiVersion: extensions.kubesphere.io/v1alpha1
kind: JSBundle
metadata:
  name: fluid-ui
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  rawFrom:
    configMapKeyRef:
      key: index.js
      name: fluid-ui
      namespace: {{ .Release.Namespace }}
{{- end }}

