{{ if .Values.crdUpgrade.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ include "fluid.namespace" . }}
  name: fluid-crds-upgrade-{{ replace "." "" .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
{{- if .Values.crdUpgrade.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.crdUpgrade.ttlSecondsAfterFinished }}
{{- end }}
  template:
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: fluid-crds-upgrade
      containers:
        - name: fluid-crds-upgrade
          image: {{ include "fluid.controlplane.imageTransform" (list .Values.crdUpgrade.imagePrefix .Values.crdUpgrade.imageName .Values.crdUpgrade.imageTag . ) }}
          command:
            - bash
            - -c
            - |
              set -e

              echo "🚀 Running CRD upgrade..."
              chmod +x /fluid/upgrade-crds.sh
              /fluid/upgrade-crds.sh

              echo "✅ CRD upgrade succeeded. Now labeling CRDs ending with data.fluid.io ..."
              for crd in $(kubectl get crd -o name | grep 'data\.fluid\.io$'); do
                kubectl label $crd kubesphere.io/resource-served='true' --overwrite
              done

              echo "🎉 All matching CRDs labeled successfully."
      restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "update", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluid-crds-upgrade
subjects:
  - kind: ServiceAccount
    name: fluid-crds-upgrade
    namespace: {{ include "fluid.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluid-crds-upgrade
  namespace: {{ include "fluid.namespace" . }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
{{- end }}
